apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-deployment
  ports:
    - protocol: TCP
      name: http
      port: 8001
      targetPort: 8001
  type: LoadBalancer